Task/gsk 1035 add lang detection
Giskard-AI/giskard pull request #1014
Opened 2023-05-16 13:45 UTC by mathieuroques

I used detect_lang and I support english and french

2023-05-16 14:34 UTC, mattbit commented
@mathieuroques could you fix the conflicts with the base branch?

2023-05-16 15:57 UTC, mathieuroques commented
Ok let me handle this

2023-05-17 10:26 UTC, mathieuroques commented
@mattbit the conflicts have been resolved

2023-05-22 11:03 UTC, mathieuroques commented
Just fixed conflicts and the failing test

2023-05-22 13:34 UTC, mattbit requested changes

2023-05-22 13:34 UTC, mattbit commented on python-client/giskard/scanner/robustness/text_transformations.py
> +        language = detect_langs(x)[0].lang
This should be calculated once in dataset text metadata provider (search `TextMetadataProvider`), and than accessed at the dataset level with `dataset.column_meta["my_textual_column", "text"].language`.

2023-05-22 13:35 UTC, mattbit commented on python-client/giskard/scanner/robustness/entity_swap.py
Can we put this into some csv or similar and load them only if needed?

2023-05-31 06:14 UTC, merged