Fix transformation issue
Giskard-AI/giskard pull request #1253
Opened 2023-07-22 12:33 UTC by mathieuroques

Now numerical values are supported

2023-07-22 12:35 UTC, mathieuroques commented
I struggle to add drop-down selector to column_name and default value to mad_num
<img width="879" alt="image" src="https://github.com/Giskard-AI/giskard/assets/84331949/09739d39-87bb-43c9-b2c9-57c44919f1f9">

2023-07-22 12:41 UTC, mathieuroques commented
Not sure we need the save transformation CTA anymore as we can add it directly in the default config

2023-07-24 12:26 UTC, mathieuroques commented
@rabah-khalek It should be ok now

2023-07-24 14:32 UTC, rabah-khalek approved these changes
I just left you a small comment on the docstring of `mad_transformation`

2023-07-24 14:32 UTC, rabah-khalek commented on python-client/giskard/ml_worker/testing/functions/transformation.py
> +    Add 3 times the MAD value to the column
This should rather be:
```py
"""
Add 3 times the value_added to the column, or if unavailable, add 3 times the MAD value.
"""
```

2023-07-24 14:36 UTC, rabah-khalek requested changes

2023-07-24 14:36 UTC, rabah-khalek commented on python-client/giskard/push/utils.py
> +def compute_mad(x):
I would also suggest to use the scipy stats method, it's fast and more transparent. The only down side could be the version compatibility, but as long as it works with the scipy that we ship, should be fine. 
![Screenshot 2023-07-24 at 16 35 10](https://github.com/Giskard-AI/giskard/assets/32709181/6e53ca85-97bd-48ff-a3cc-2a1bd3cca18c)

2023-07-24 15:36 UTC, merged