[GSK-1505] Integration with W&B
Giskard-AI/giskard pull request #1288
Opened 2023-08-02 11:58 UTC by rabah-khalek

# Features

## Prerequisites
1. Create a wandb account [here](https://wandb.ai/signup).
2. Open your docker app
3. Install python package and server
    ```shell
    pip install wandb
    wandb login --relogin # input the API key you get from the website
    wandb server start --upgrade # this will download the docker images if they're not already downloaded
    ```
## Features
```py
import giskard, wandb
# [...] wrap model and dataset with giskard
results = giskard.scan(giskard_model, giskard_dataset)

# log scan results
wandb.login()
results.to_wandb()
```
# Todo

- [ ] log test suite (@rabah-khalek)
- [ ] log model artifact (@rabah-khalek)
- [ ] log dataset artifact (@AbSsEnT)
- [ ] think of other objects we can log (@AbSsEnT and @rabah-khalek)

2023-08-25 10:28 UTC, andreybavt requested changes
Generally speaking looks good to me, I left a few non-major comments

2023-08-25 10:28 UTC, andreybavt commented on python-client/pyproject.toml
> +    "wandb"
no need to add it to the `proto` group

2023-08-25 10:28 UTC, andreybavt commented on python-client/giskard/models/shap_result.py
> +    only_highest_proba: Optional[bool] = True
it's not Optional, it's just bool since the default is `True` and not `None`

2023-08-25 10:28 UTC, andreybavt commented on python-client/giskard/models/shap_result.py
> +                        "cat_feat_cnt": len([c for c, t in self.feature_types.items() if t == "category"]),
not a big issue, but you can do 1 pass over the list and build the counters instead of doing 3 iterations

2023-08-25 10:28 UTC, andreybavt commented on python-client/giskard/datasets/base/__init__.py
> +                    "dataset_cat_col_cnt": len([c for c, t in self.column_types.items() if t == "category"]),
same comment about iterating 3 times as in another similar place

2023-08-28 08:08 UTC, rabah-khalek commented on python-client/pyproject.toml
> +    "wandb"
This is under the `test` group in fact

2023-08-30 07:33 UTC, andreybavt approved these changes
LGTM

2023-08-30 07:33 UTC, merged