Update README.md
Giskard-AI/giskard pull request #1310
Opened 2023-08-14 12:35 UTC by mathieuroques

2023-08-14 16:50 UTC, mathieuroques commented
- [] Create diagram for first page
- [] Replace screenshot by gif
- [] Clean the `hello word` script

2023-08-17 17:19 UTC, luca-martial requested changes

2023-08-17 17:19 UTC, luca-martial commented on README.md
> +  <summary>About the ML worker</summary>
"What is a ML worker?" -> should be a question

2023-08-17 17:19 UTC, luca-martial commented on README.md
> +# ❓ FAQ
You can add a "Where can I get more help?" or something similar and link the discord

2023-08-17 17:19 UTC, luca-martial commented on README.md
>  Read this [guide](CONTRIBUTING.md) to get started.
should be on the same line as sentence above

2023-08-17 17:19 UTC, luca-martial commented on README.md
>  🌟 [Leave us a star](https://github.com/Giskard-AI/giskard), it helps the project to get discovered by others and keeps us motivated to build awesome open-source tools! 🌟
before the leave us a star section there should be a "Join our thriving community ... " with a link to our discord

2023-08-25 15:20 UTC, mathieuroques commented
> TODO @luca-martial :
> 
> * [x]  Record higher quality gif
> * [x]  Write better Open-source and Closed-source description
> * [ ]  Decide if FAQ should be technical or not technical
> * [ ]  Add more references to our documentation
> * [x]  Write introduction paragraph about gsk
> * [x]  Add python version !!
> * [ ]  Create diagram for first page

2023-09-14 12:20 UTC, luca-martial approved these changes

2023-09-14 12:21 UTC, luca-martial commented
@andreybavt this looks good to go on my end. We can make more changes on wording once Hub goes closed-source

2023-09-15 21:24 UTC, merged