Fixed issues with upload
Giskard-AI/giskard pull request #1348
Opened 2023-08-29 12:44 UTC by Googleton

PR made on @kevinmessiaen's behalf to quickly merge it 🙏

2023-08-29 12:57 UTC, andreybavt requested changes

2023-08-29 12:57 UTC, andreybavt commented on backend/src/main/java/ai/giskard/service/TransformationFunctionService.java
> +        if (Strings.isBlank(function.getDisplayName())) {
@kevinmessiaen  it's a pity to duplicate this part 3 times, can you refactor it to share between the 3 function types?

for example by extracting a common method like
```
    @NotNull
    public static <T extends Callable> T intializeFunction(T function, CallableRepository repo) {
        if (function.getArgs() != null) {
            function.getArgs().forEach(arg -> arg.setFunction(function));
        }

        if (Strings.isBlank(function.getDisplayName())) {
            function.setDisplayName(function.getModule() + "." + function.getName());
        }

        function.setVersion(repo.countByDisplayName(function.getDisplayName()) + 1);

        return function;
    }
```

2023-09-06 09:35 UTC, andreybavt approved these changes
looks good, tested on tests and slicing functions (including rule based ones)

2023-09-06 10:53 UTC, kevinmessiaen approved these changes

2023-09-06 10:53 UTC, merged