Fix/improve unreliable test
Giskard-AI/giskard pull request #1399
Opened 2023-09-12 17:31 UTC by Hartorn

2023-09-14 10:01 UTC, andreybavt requested changes

2023-09-14 10:01 UTC, andreybavt commented on python-client/tests/test_logging.py
> +    assert abs(duration.microseconds - 10**5) / 10**5 < 0.1
let's use a pytest utility here:

```
import pytest

def test_timer():
    sleep_sec = 0.1
    timer = Timer()
    time.sleep(sleep_sec)
    duration = timer.stop()
    assert duration.microseconds == pytest.approx(sleep_sec * 10**6, 0.10)
```

2023-09-15 11:48 UTC, andreybavt approved these changes

2023-09-15 11:50 UTC, rabah-khalek commented
@andreybavt I don't think this PR should've been merged before updating the branch with main. 

The main reason @Hartorn introduced these changes is because of the PR of single column that is now reverted.

2023-09-15 13:15 UTC, merged