Allow to move PyTorch model from HF to the given device
Giskard-AI/giskard pull request #1481
Opened 2023-10-17 08:53 UTC by Inokinoki

## Description

TF model could also be PyTorch NN module. We need use `to(device)` to move and run the models to GPU.

## Related Issue

## Type of Change

- [ ] 📚 Examples / docs / tutorials / dependencies update
- [x] 🔧 Bug fix (non-breaking change which fixes an issue)
- [ ] 🥂 Improvement (non-breaking change which improves an existing feature)
- [ ] 🚀 New feature (non-breaking change which adds functionality)
- [ ] 💥 Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🔐 Security fix

## Checklist

- [ ] I've read the [`CODE_OF_CONDUCT.md`](https://github.com/Giskard-AI/ai-inspector/blob/master/CODE_OF_CONDUCT.md) document.
- [ ] I've read the [`CONTRIBUTING.md`](https://github.com/Giskard-AI/ai-inspector/blob/master/CONTRIBUTING.md) guide.
- [ ] I've updated the code style using `make codestyle`.
- [ ] I've written tests for all new methods and classes that I created.
- [ ] I've written the docstring in Google format for all the methods and classes that I used.

2023-10-17 09:51 UTC, rabah-khalek requested changes
it's not a bad idea to have a `device` field for `HuggingFaceModel` but this needs to be done properly taking into account two things:
- `device` has to be saved in the meta files (see how it's done for `PyTorchModel`)
- the HF model could be a tensorflow one, so we should first check if `hasattr(model, "device")`

2023-10-17 09:55 UTC, mattbit requested changes

2023-10-17 09:55 UTC, mattbit commented on giskard/models/huggingface.py
> +            self.deivce = "cpu"
Typo `deivce`

2023-10-17 09:55 UTC, mattbit commented on giskard/models/huggingface.py
> +            self.model = self.model.to(self.device)
- What if the device is not available?
- What if the model input is not on the same device?

2023-10-17 09:58 UTC, mattbit commented
I would be careful with this. Saving the device in the metadata for me does not necessarily make sense, since it’s something that depends on the environment.
We should thoroughly test that we are not breaking normal usage.
E.g. I upload the model from my notebook, running on GPU. Then I download it somewhere else, e.g. in CICD where I don’t have a GPU. Would it break? Would it fallback to CPU? To be checked.

Also: the preprocessing could be specific to the device? If I move the tensors around in the preprocessing function, would that break model_predict? Is there a fallback?

2023-10-17 10:02 UTC, rabah-khalek commented
yeah but you'd need to change your `prediction_function` too if you do such transitions of env. It's not like you're protected if `device` is not there. You'd have to create a new model either way.

2023-10-18 07:14 UTC, Inokinoki commented
After the discussion with @rabah-khalek I think that providing a special prediction function is enough for those who are using GPU. So close this

2023-10-18 07:14 UTC, closed without merging