[GSK-2035] Added num_samples to prompt injection detector
Giskard-AI/giskard pull request #1533
Opened 2023-10-31 18:29 UTC by rabah-khalek

Random sampling across all prompt injections (disabled by default)

2023-11-03 15:48 UTC, mattbit requested changes

2023-11-03 15:48 UTC, mattbit commented on giskard/llm/prompt_injection/data.py
> +    pi_prompt_data.ALL_OPENAI_PLAYGROUND_PROMPTS[i]["instruction"] = ""
Can we solve the problem at the source instead of filtering at runtime?

2023-11-03 15:48 UTC, mattbit commented on giskard/llm/prompt_injection/data.py
> +    if num_samples is not None:
To me, this still looks like a lot complication for no foreseeable use

2023-11-03 15:49 UTC, mattbit requested changes
Avoid for lool at module level

2023-11-06 11:22 UTC, mattbit commented
Let’s put this on hold

2023-11-13 15:12 UTC, rabah-khalek commented
Superseded by https://github.com/Giskard-AI/giskard/pull/1602

2023-11-13 15:12 UTC, closed without merging