Simplify scan metadata
Giskard-AI/giskard pull request #1772
Opened 2024-01-29 16:19 UTC by luca-rossi

2024-01-31 17:15 UTC, mattbit requested changes
All good but please remove extraneous changes

2024-01-31 17:15 UTC, mattbit commented on giskard/slicing/tree_slicer.py
This doesn't belong here

2024-02-01 10:34 UTC, luca-rossi commented on giskard/slicing/tree_slicer.py
Sorry, didn't branch out correctly

2024-02-05 09:59 UTC, mattbit approved these changes

2024-02-05 11:39 UTC, merged