GSK-2887 Upload tests with project when uploading a suite
Giskard-AI/giskard pull request #1837
Opened 2024-03-07 04:34 UTC by kevinmessiaen

2024-03-07 10:12 UTC, Inokinoki requested changes
LGTM
Just some comments to be removed or polished.

Not related to this PR:
We will neither have global resources anymore, nor "internal worker". So we can also cleanup the `Optional[GiskardClient]`, can we create a card for this?

2024-03-07 10:12 UTC, Inokinoki commented on tests/communications/test_websocket_actor.py
>  # FIXME: Internal worker cannot yet load callable due to yaml deserialization issue
idem.

2024-03-07 10:12 UTC, Inokinoki commented on tests/test_artifact_download.py
>          # Prepare global URL
Can be changed to prepare URLs, cuz we have no more global artefacts

2024-03-11 06:41 UTC, kevinmessiaen commented
> LGTM Just some comments to be removed or polished.
> 
> Not related to this PR: We will neither have global resources anymore, nor "internal worker". So we can also cleanup the `Optional[GiskardClient]`, can we create a card for this?

I've updated th PR and remove the optional client

2024-03-14 18:40 UTC, Inokinoki approved these changes
LGTM! Thanks!

2024-03-15 02:12 UTC, merged