[GSK-3361] Model predictions are casted to double by default in regression mode
Giskard-AI/giskard pull request #1857
Opened 2024-03-21 09:55 UTC by bmalezieux

## Description

## Related Issue

## Type of Change

- [ ] 📚 Examples / docs / tutorials / dependencies update
- [ ] 🔧 Bug fix (non-breaking change which fixes an issue)
- [ ] 🥂 Improvement (non-breaking change which improves an existing feature)
- [ ] 🚀 New feature (non-breaking change which adds functionality)
- [ ] 💥 Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🔐 Security fix

## Checklist

- [ ] I've read the [`CODE_OF_CONDUCT.md`](https://github.com/Giskard-AI/ai-inspector/blob/master/CODE_OF_CONDUCT.md) document.
- [ ] I've read the [`CONTRIBUTING.md`](https://github.com/Giskard-AI/ai-inspector/blob/master/CONTRIBUTING.md) guide.
- [ ] I've written tests for all new methods and classes that I created.
- [ ] I've written the docstring in Google format for all the methods and classes that I used.
- [ ] I've updated the `pdm.lock` running `pdm update-lock` (only applicable when `pyproject.toml` has been
  modified)

2024-03-21 10:47 UTC, rabah-khalek commented
@Hartorn, @kevinmessiaen it seems that this is not breaking anything on the side of the library. @bmalezieux is verifying it on the hub side.

2024-03-21 11:29 UTC, bmalezieux commented
> @Hartorn, @kevinmessiaen it seems that this is not breaking anything on the side of the library. @bmalezieux is verifying it on the hub side.

It works for our current project, but maybe this would break in other scenarios.

2024-03-21 11:47 UTC, Hartorn requested changes

2024-03-21 11:47 UTC, Hartorn commented on giskard/models/base/wrapper.py
> +        # if self.is_regression:
Just remove the line ;)

2024-03-21 11:48 UTC, Hartorn commented
> > @Hartorn, @kevinmessiaen it seems that this is not breaking anything on the side of the library. @bmalezieux is verifying it on the hub side.
> 
> It works for our current project, but maybe this would break in other scenarios.

I will try to run the e2e tests to make sure of it
Did you try on the regression notebooks in docs/reference/notebooks ?

2024-03-21 12:00 UTC, Hartorn commented
Running in https://github.com/Giskard-AI/giskard-hub/actions/runs/8374478584/job/22929809288?pr=544

2024-03-25 10:55 UTC, Hartorn approved these changes

2024-03-25 10:56 UTC, Hartorn commented
Tested on insurance_prediction_lgbm and hotel_text_regression

2024-03-25 11:18 UTC, merged