Added documentation on which tag to use when using the scan's `only` param for each detector
Giskard-AI/giskard pull request #2033
Opened 2024-09-23 06:11 UTC by kevinmessiaen

## Description

## Related Issue

## Type of Change

- [ ] 📚 Examples / docs / tutorials / dependencies update
- [ ] 🔧 Bug fix (non-breaking change which fixes an issue)
- [ ] 🥂 Improvement (non-breaking change which improves an existing feature)
- [ ] 🚀 New feature (non-breaking change which adds functionality)
- [ ] 💥 Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🔐 Security fix

## Checklist

- [ ] I've read the [`CODE_OF_CONDUCT.md`](https://github.com/Giskard-AI/ai-inspector/blob/master/CODE_OF_CONDUCT.md) document.
- [ ] I've read the [`CONTRIBUTING.md`](https://github.com/Giskard-AI/ai-inspector/blob/master/CONTRIBUTING.md) guide.
- [ ] I've written tests for all new methods and classes that I created.
- [ ] I've written the docstring in Google format for all the methods and classes that I used.
- [ ] I've updated the `pdm.lock` running `pdm update-lock` (only applicable when `pyproject.toml` has been
  modified)

2024-09-24 10:40 UTC, henchaves requested changes

2024-09-24 10:40 UTC, henchaves commented on giskard/scanner/calibration/overconfidence_detector.py
> +    You can explicitly run this scanner by adding the tag "overconfidence" in the `only` parameter of the scan method.
we should replace the word `scanner` by `detector` in all detectors

2024-09-24 10:40 UTC, henchaves commented on giskard/scanner/robustness/ethical_bias_detector.py
> +    tags=["ethical_bias", "robustness", "classification", "regression", "ethical_bias"],
`ethical_bias` is repeated here

2024-09-25 12:41 UTC, gopi-nath commented
Hey

These detectors aren't working
Please check here

https://github.com/Giskard-AI/giskard/issues/1984#issuecomment-2373970314

2024-09-26 10:35 UTC, henchaves approved these changes

2024-09-27 05:18 UTC, merged