GSK-288 In addition with the search bar, added a filter toggle. Finished
Giskard-AI/giskard pull request #272
Opened 2022-09-27 08:34 UTC by thomasabou01

2022-09-28 08:14 UTC, thomasabou01 commented
Everything is building well on my side, I just modified the test.vue file...

2022-09-28 15:04 UTC, andreybavt requested changes

2022-09-28 15:04 UTC, andreybavt commented on giskard-frontend/src/views/main/project/Tests.vue
> +        .reduce((partial) => partial + 1, 0);
for example:
```
.filter((test) => !result || test.status == result).length;
```

2022-09-30 16:08 UTC, andreybavt approved these changes

2022-09-30 16:08 UTC, merged