#597 - Change loading to indefinite progress bar for Inspector Launcher
Giskard-AI/giskard pull request #613
Opened 2022-12-20 09:11 UTC by Googleton

## Description

- [x] Change loading from spinner to indefinite progress bar
- [x] Migrate InspectorLauncher.vue to Composition API

## Related Issue

#432 => InspectorLauncher.vue migrated

2022-12-21 12:16 UTC, alexcombessie requested changes

2022-12-21 12:16 UTC, alexcombessie commented on frontend/src/views/main/project/InspectorLauncher.vue
> +        <span>Scoring the entire dataset. This operation can take a while...</span>
Would just need to add "Scoring the entire dataset of {fileSizeInHumanReadableFormat}"

2022-12-23 18:32 UTC, alexcombessie reviewed
Thanks @Googleton ! I verified that it works well functionally.

On the code part, I see several changes in the TypeScript part that are not directly related to the issue. Is it pure refactoring or have you changed the actual logic of functions?

Also, what is the function of the vue2-vue3-migration.md file in this PR?

2022-12-23 19:32 UTC, Googleton commented
Those TypeScript changes are related to #432 which is a migration from Vue 2's Options API to Vue 3's Composition API
The general rule of thumb, if we modify a Vue 2 component, migrate it to Vue 3 in the same PR so the migration progresses without dedicating a larger amount of time to do it.

The documentation file is here as a cheatsheet to easily find common patterns in that migration

2022-12-26 18:06 UTC, alexcombessie commented
@Googleton okay thanks for the explanation. In that case I will let @andreybavt lead the code review of the Vue3 migration.
On the functional side, the PR is okay for me. Thanks for your good work!

PS: merry Christmas in delay 🎄

2022-12-29 11:59 UTC, andreybavt approved these changes

2022-12-29 11:59 UTC, merged

2023-01-11 10:27 UTC, rabah-khalek commented
I really like this bar addition, can we just find an alternative to `NaN`?
<img width="1588" alt="Screenshot 2023-01-11 at 11 23 27" src="https://user-images.githubusercontent.com/32709181/211782323-3e24f419-edab-48e6-8fb4-d872f8407ee4.png">