497 need to be able to rename datasets and models from the UI
Giskard-AI/giskard pull request #638
Opened 2023-01-06 11:15 UTC by kevinmessiaen

## Description

Added the possibility to rename dataset and models for admin and project owner

## Related Issue

Migration of component:
- Models.vue
- Datasets.vue

## Type of Change

- [ ] 📚 Examples / docs / tutorials / dependencies update
- [ ] 🔧 Bug fix (non-breaking change which fixes an issue)
- [x] 🥂 Improvement (non-breaking change which improves an existing feature)
- [ x 🚀 New feature (non-breaking change which adds functionality)
- [ ] 💥 Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🔐 Security fix

## Checklist

- [x] I've read the [`CODE_OF_CONDUCT.md`](https://github.com/Giskard-AI/ai-inspector/blob/master/CODE_OF_CONDUCT.md) document.
- [x] I've read the [`CONTRIBUTING.md`](https://github.com/Giskard-AI/ai-inspector/blob/master/CONTRIBUTING.md) guide.
- [ ] I've updated the code style using `make codestyle`.
- [ ] I've written tests for all new methods and classes that I created.
- [ ] I've written the docstring in Google format for all the methods and classes that I used.

2023-01-09 14:34 UTC, andreybavt commented
Since the name is the only property we allow to edit, I'd place the edit/save buttons next to it, otherwise, there's a little back and forth required to enable editing and then save.

![image](https://user-images.githubusercontent.com/7889985/211329558-5594db90-c653-4601-9b59-66692a37cd20.png)

2023-01-09 14:34 UTC, andreybavt requested changes

2023-01-09 14:34 UTC, andreybavt commented on backend/src/main/java/ai/giskard/service/DatasetService.java
> +        if (!SecurityUtils.isCurrentUserAdmin() && !SecurityUtils.isCurrentUserInside(dataset.getProject().getOwner())) {
this check is essentially the same as `canWriteProject`, let's use the same access validation as for dataset creation, e.g. `ai/giskard/web/rest/controllers/UploadController.java:56`

2023-01-09 14:34 UTC, andreybavt commented on backend/src/main/java/ai/giskard/web/rest/controllers/ModelController.java
> +        if (!SecurityUtils.isCurrentUserAdmin() && !SecurityUtils.isCurrentUserInside(model.getProject().getOwner())) {
same comment as for datasets

2023-01-09 14:34 UTC, andreybavt commented on frontend/src/views/main/project/Datasets.vue
> +    mixpanel.track('Update dataset name', {id: editedDataset.value.id});
good job adding tracking 👍

2023-01-09 14:35 UTC, andreybavt commented on frontend/src/views/main/project/Datasets.vue
> +const editedDataset = ref<FileDTO | null>(null);
the type defined should rather be `DatasetDTO`, same for editedDataset

2023-01-10 08:17 UTC, kevinmessiaen commented
> Member

I've updated the UI to have the button next to the edited field

2023-01-11 15:49 UTC, andreybavt approved these changes

2023-01-11 15:50 UTC, merged