working on tensorflow implementation
Giskard-AI/giskard pull request #672
Opened 2023-01-17 11:59 UTC by rabah-khalek

daughter of daughter of https://github.com/Giskard-AI/giskard/pull/618, https://github.com/Giskard-AI/giskard/pull/661, https://github.com/Giskard-AI/giskard/pull/662 and https://github.com/Giskard-AI/giskard/pull/664

Working on pytorch mlflow integration.

- [ ] Decide on how to wrap the tensorflow models, specially those of HuggingFace
- [ ] Verify implementation with the imdb [notebook](https://github.com/Giskard-AI/giskard-examples/blob/task/GSK-273_Tensorflow_model_integration_with_Adam_optimizer_IMDB_notebook/Text_classification_Using_Tensorflow_Neural_Network.ipynb)
- [ ] Verify implementation with all the tensorflow unit-tests implemented in https://github.com/Giskard-AI/giskard/pull/376

2023-02-22 11:38 UTC, rabah-khalek commented
The unit-test that I was planning to add, turned out to be a hugging face model, I'll defer these to another branch, and another class dedicated for transformers from hugging face as we discussed. Thereby this branch can be merged.

2023-02-22 15:50 UTC, andreybavt requested changes

2023-02-22 15:50 UTC, andreybavt commented on python-client/tests/tensorflow/test_mnist.py
> +    #test_labels = test_labels[:100]
commented code can be removed

2023-02-22 15:50 UTC, andreybavt commented on python-client/tests/tensorflow/test_mnist.py
> +    #test_images = test_images[:100].reshape(-1, 28 * 28) / 255.0
commented code can be removed

2023-02-22 15:50 UTC, andreybavt commented on python-client/tests/tensorflow/test_mnist.py
> +        # enron = client.create_project('test-project', "Email Classification", "Email Classification")
commented code can be removed

2023-02-22 15:50 UTC, andreybavt commented on python-client/tests/tensorflow/test_text_classification_tfhub.py
> +#tfhub_handle_encoder = 'https://tfhub.dev/tensorflow/small_bert/bert_en_uncased_L-4_H-512_A-8/1'
commented code can be removed

2023-02-22 15:50 UTC, andreybavt commented on python-client/tests/tensorflow/test_text_classification_tfhub.py
> +        # enron = client.create_project('test-project', "Email Classification", "Email Classification")
commented code can be removed

2023-02-22 17:13 UTC, rabah-khalek commented
Done.

2023-02-27 20:35 UTC, andreybavt requested changes
mostly last minor comments

2023-02-27 20:35 UTC, andreybavt commented on python-client/giskard/core/model.py
> +    def post_processing(self, raw_prediction):
to make it less confusing for an end user which post processing function he has to override, I'd make this method private by adding `_` prefix

2023-02-27 20:35 UTC, andreybavt commented on python-client/giskard/core/model.py
> +                          "We automatically infered the second class prediction but please make sure that \n" + \
infe`rr`ed

2023-02-27 20:35 UTC, andreybavt commented on python-client/giskard/core/model.py
> +        warning_message = f"\nYour binary classification model prediction is of the shape {raw_prediction.shape}. \n" + \
nitpick: `warning_message` can be initialized inside `if is_binary_classification`

2023-02-27 21:37 UTC, merged