Giskard Server CLI
Giskard-AI/giskard pull request #938
Opened 2023-04-17 11:23 UTC by Googleton

## Description

2023-04-17 14:08 UTC, andreybavt requested changes
I think it's also worth adding a test for _fetch_latest_tag to ensure that we detect a case when the tag format accidentally changes

2023-04-17 14:08 UTC, andreybavt commented on python-client/giskard/commands/cli_server.py
> +    # TODO: Maybe cache it ?
I don't think we should, it's not a heavy operation to read it and there's no cache invalidation problem to handle

2023-04-17 14:09 UTC, andreybavt commented on python-client/giskard/commands/cli_server.py
> +client = docker.from_env()
We should also gracefully handle the situation when docker isn't installed/running

2023-04-19 17:03 UTC, andreybavt commented
In the current implementation neither `pgdata` nor `giskard-home` aren't persisted in docker volumes. In this case whenever you delete the container (by upgrading Giskard for example), the data will be lost

2023-04-20 04:52 UTC, Googleton commented
Pushed volume handling but there is an issue: 

Supervisord uses a small script to init the database if it doesn't exist (checking if the folder at $PGDATA exists). Since I use volumes now, the condition is always false, which means it tries to do pgsql's initdb over an existing folder, fails and the db won't start. Looking for a fix

2023-04-24 19:51 UTC, merged