[GSK-959] Feature: Create a debugger tab
Giskard-AI/giskard pull request #955
Opened 2023-04-20 15:15 UTC by henchaves

## Description

The idea of this PR is to implement a new tab called **DEBUGGER**.
Within this tab, the user can directly create a new debugging session (previously called "inspection") without having to move to MODELS tab.
Also, the user can interact with other sessions that were previously created in the same project.

## Related Issue

[GSK-959 (via Linear)](https://linear.app/giskard/issue/GSK-959/create-a-debugger-tab)

## Type of Change

- [ ] 📚 Examples / docs / tutorials / dependencies update
- [ ] 🔧 Bug fix (non-breaking change which fixes an issue)
- [ ] 🥂 Improvement (non-breaking change which improves an existing feature)
- [ ] 🚀 New feature (non-breaking change which adds functionality)
- [x] 💥 Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🔐 Security fix

2023-04-20 16:07 UTC, kevinmessiaen requested changes

2023-04-24 12:56 UTC, henchaves commented on backend/src/main/java/ai/giskard/service/InspectionService.java
> +        inspections.removeIf(inspection -> !inspection.getModel().getProject().getId().equals(projectId));
@kevinmessiaen like that?
<img width="1186" alt="image" src="https://user-images.githubusercontent.com/44180294/234002528-333dfd50-a0c0-4d29-a0f2-7f9226dff2c2.png">

2023-04-24 13:01 UTC, kevinmessiaen commented on backend/src/main/java/ai/giskard/service/InspectionService.java
> +        inspections.removeIf(inspection -> !inspection.getModel().getProject().getId().equals(projectId));
Well it should be working without the `@Query` annotation: https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#repositories.query-methods.details

2023-04-24 16:11 UTC, kevinmessiaen approved these changes

2023-04-25 11:59 UTC, merged