GSK-844 Push feature
Giskard-AI/giskard pull request #971
Opened 2023-04-26 07:48 UTC by Googleton

## Description

Implementation of the Push feature

2023-05-17 15:56 UTC, Googleton commented on backend/src/main/java/ai/giskard/service/InspectionService.java
> +
```suggestion
```

2023-05-22 10:30 UTC, andreybavt commented
I'm getting an error when no internal worker is connected. @Googleton I don't understand why we're always using an internal worker for pushes generation, it should be project dependant, otherwise you won't be able to execute a model requiring custom python dependencies
<img width="1840" alt="Screenshot 2023-05-22 at 12 21 57" src="https://github.com/Giskard-AI/giskard/assets/7889985/ccdd42ec-46f2-4af4-80cf-d7de960b69f5">

2023-05-22 10:33 UTC, andreybavt commented
z-index issue

<img width="645" alt="image" src="https://github.com/Giskard-AI/giskard/assets/7889985/2cde13a1-e271-4488-84a5-b8fde6fc64fd">

2023-05-22 11:03 UTC, andreybavt requested changes

2023-05-22 11:03 UTC, andreybavt commented on python-client/giskard/push/transformation.py
> +text = "She her the brown fox jumps over the lazy dog in Sydney, was christian"
this should be a unit test

2023-05-22 11:03 UTC, andreybavt commented on python-client/tests/test_push.py
> +# def test_perturbation_text(enron_model, enron_data):
cleanup here and below

2023-05-22 13:41 UTC, mattbit commented on python-client/giskard/push/transformation.py
> +nlp = spacy.load('en_core_web_sm')
We don’t want to do this here!!!

2023-05-22 13:42 UTC, mattbit commented on python-client/giskard/push/transformation.py
> +        self.nlp = spacy.load("en_core_web_sm")
What if this fails? This requires the user to have installed the extra spacy module `en_core_web_sm`.

2023-05-22 14:12 UTC, mattbit requested changes
A few things to check on the Python part:
- `Push` class might need to be refactored in a cleaner way
- Dependency with `spacy`: do we need this? do we commit to adding this to the dependencies?
- Perturbation-based push has a significant overlap with the scan feature: can we isolate the transformations and reuse them in both push and scan?

2023-05-22 14:12 UTC, mattbit commented on python-client/giskard/push/perturbation.py
> +    return val + 3 * mad  # 1.2  # 20% perturbation
This is roughly 2 σ for a normal distribution. To me it looks like a big perturbation! Are we sure we want this? E.g. if value is close to the mean, we would be pushing it to the 95% percentile.

2023-05-22 14:12 UTC, mattbit commented on python-client/giskard/push/perturbation.py
> +    return val + 3 * mad  # 1.2  # 20% perturbation
Also: we only increase the value! Perturbation could be in the negative direction. (Maybe I am missing something?)

2023-05-22 14:12 UTC, mattbit commented on python-client/giskard/push/transformation.py
Quite an overlap with scan perturbation, can we merge the common parts?

2023-05-25 15:35 UTC, mathieuroques commented on python-client/giskard/ml_worker/server/ml_worker_service.py
> +        contribs = contribution(model, dataset, request.rowidx)
Done

2023-05-25 15:38 UTC, mathieuroques commented on python-client/giskard/push/contribution.py
> +        # re = ds.__dict__
Done

2023-05-25 15:38 UTC, mathieuroques commented on python-client/giskard/push/contribution.py
> +        prediction = model.model.predict(ds.df.iloc[[idrow]])
Resolved

2023-05-25 15:42 UTC, mathieuroques commented on python-client/giskard/push/transformation.py
> +text = "She her the brown fox jumps over the lazy dog in Sydney, was christian"
I removed this unused file

2023-05-25 15:42 UTC, mathieuroques commented on python-client/tests/test_push.py
> +# def test_perturbation_text(enron_model, enron_data):
Done

2023-05-25 15:42 UTC, mathieuroques commented on python-client/giskard/push/transformation.py
> +nlp = spacy.load('en_core_web_sm')
File deleted

2023-05-25 15:47 UTC, mathieuroques commented on python-client/giskard/push/transformation.py
File deleted

2023-06-16 14:25 UTC, andreybavt commented
Closing this PR as @Googleton will open a new one for the branch where the conflicts are merged. We're using this branch as a reference for conflict resolution

2023-07-07 13:41 UTC, closed without merging